# Generated by Django 2.2.4 on 2020-01-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000, unique=True)),
                ('is_saved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'url',
            },
        ),
    ]
